### ISSUE TITLE
doing `<Title>{[].length} items</Title>` in SSR results in "0, items" while in CSR it results in "0 items" as it should

### ISSUE THREAD

**Issue by huseeiin** [solidjs/solid-meta#45] opened 2024-03-20 08:10 UTC
reproduction:
```tsx
export function App() {
	return (
		<MetaProvider>
			<Title>{[].length} items</Title>
		</MetaProvider>
	);
}

const html = await renderToStringAsync(() => <App />);

const head = getAssets();
```

**Comment by indeyets** [comment] 2024-03-22 16:46
duplicate of #37

**Closed** 2024-05-15 15:11 UTC
